#NOMBRE DEL FLUJO DE TRABAJO (PIPELINE)
name: BuildRepositoryWorkFlow

on:
  #SERA EJECUTADO CUANDO SE HAGA UN PUSH A LAS SIGUIENTES RAMAS
  push:
    branches: ["main", "miRamita"]

  #VA EJECUTAR LOS SIGUIENTES TRABAJOS (PARA COMPILAR)
jobs:
  build:
    runs-on: ubuntu-latest #SE EJECUTA BAJO EL SO DE LINUX UBUNTU

    steps:
      #PASO POR DEFECTO (SE ENCARGA DE CLONAR EL REPOSITORIO ACTUAL EN EL RUNNER)
      - name: Clonar Repositorio
        uses: actions/checkout@v3
      
      #PASO PARA GUARDAR LOS ARCHIVOS COMPILADOS DE LA PWA COMO ARTEFACTOS
      - name: Guardar artefactos
        uses: actions/upload-artifact@v3
        with:
          name: pwa-artifacts
          path: ./dist

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: main